### ISSUE TITLE
More information?

### ISSUE THREAD

**Issue by markudevelop** [EvgenyKashin/TensorPoker#1]
Hello Evgeny

Thanks for sharing this great example, I was wondering if there is more information on what specfic  strategy or paper is it based on and what kind of result were achieved? I trained it for few hours, but still couldn't make sense on how good it's and on what to look for?

Thanks!

**Comment by EvgenyKashin** [comment]
Hi, I'm glad it was useful for you. I based feature extraction on this paper https://arxiv.org/abs/1509.06731 and used standart DQN for this specific reinforcment learning task. Also I read https://arxiv.org/abs/1603.01121 paper that has a lot of useful ideas. You should train it for a much more hours (mb with GPU) to achive great result as I understand
